import React from 'react';
import { FileText } from 'lucide-react';
import { API_BASE } from '../api';
import { useAppState } from '../state';

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="metricTile">
      <span>{label}</span>
      <b>{value}</b>
    </div>
  );
}

export default function OverviewPage() {
  const s = useAppState();
  const metrics = s.results?.model?.metrics || {};
  const fairness = s.results?.fairness?.overall_risk || '—';
  const model = s.results?.model?.selected_model || '—';
  const dist = s.results?.eda?.target_distribution;
  const distText = dist ? Object.entries(dist).map(([k, v]) => `${k}: ${v}`).join(', ') : '—';
  const topDrivers = (s.results?.explainability?.top_features || []).slice(0, 5);
  const recommendations: string[] = s.results?.recommendations || [];
  const insights: string[] = s.results?.insights || [];
  const llmInsights = s.results?.llm_insights;

  if (!s.datasetId) {
    return (
      <div className="page">
        <div className="card">
          <h3>Overview</h3>
          <p className="muted">Run an analysis first. Go to “Run”.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="page">
      <div className="pageHeader">
        <div>
          <h2>Results & Insights</h2>
          <p className="muted">A simple summary your HR team can act on (with downloads).</p>
        </div>
        <div className="btnRow single" style={{ maxWidth: 420 }}>
          <a className="download" href={`${API_BASE}/analysis/${s.datasetId}/report`}><FileText size={18} /> Download PDF Report</a>
        </div>
      </div>
      {llmInsights?.summary ? (
        <div className="grid one">
          <div className="card">
            <h3>LLM HR Narrative</h3>
            <p className="muted">Generated by {llmInsights.provider || 'Groq'} from Retainly's structured model, fairness, and action-plan outputs.</p>
            <div className="panelHint">{llmInsights.summary}</div>
          </div>
        </div>
      ) : null}
      <div className="grid two">
        <div className="card">
          <h3>Key findings</h3>
          <div className="metricGrid">
            <Metric label="Selected model" value={String(model)} />
            <Metric label="Fairness risk" value={String(fairness)} />
            <Metric label="Accuracy" value={Number(metrics.accuracy || 0).toFixed(3)} />
            <Metric label="Recall" value={Number(metrics.recall || 0).toFixed(3)} />
            <Metric label="Precision" value={Number(metrics.precision || 0).toFixed(3)} />
            <Metric label="F1 score" value={Number(metrics.f1 || 0).toFixed(3)} />
          </div>
          <div className="panelHint">Attrition distribution in your uploaded data: {distText}</div>
          <h4>Top drivers (what’s linked to attrition)</h4>
          {topDrivers.length ? (
            <ul>
              {topDrivers.map((d: any) => <li key={d.feature}><b>{d.feature}</b> (importance {Math.abs(Number(d.importance || 0)).toFixed(3)})</li>)}
            </ul>
          ) : (
            <p className="muted">Driver signals will appear after analysis.</p>
          )}
          <details className="detailsBox">
            <summary>Downloads (CSV / results JSON)</summary>
            <div className="btnRow single" style={{ marginTop: 10 }}>
              <a className="download secondary" href={`${API_BASE}/datasets/${s.datasetId}/download`}>Download Uploaded CSV</a>
              <a className="download secondary" href={`${API_BASE}/analysis/${s.datasetId}/results.json`}>Download Results JSON</a>
            </div>
          </details>
        </div>

        <div className="card">
          <h3>What this means (plain English)</h3>
          {insights.length ? (
            <ul>
              {insights.map((x: string, i: number) => <li key={i}>{x}</li>)}
            </ul>
          ) : (
            <p className="muted">No insights yet.</p>
          )}
          <h4>Practical actions for HR</h4>
          {recommendations.length ? (
            <ul>
              {recommendations.map((x: string, i: number) => <li key={i}>{x}</li>)}
            </ul>
          ) : (
            <p className="muted">No recommendations yet.</p>
          )}
          <div className="panelHint">If you want a one-line answer for leadership: “These are the biggest risk drivers and the safest interventions to test first.”</div>
        </div>
      </div>
    </div>
  );
}
